### ISSUE TITLE
passing tuples to office conversion doesn't work

### ISSUE THREAD

**Issue by thib3113** [yumauri/gotenberg-js-client#11]
On lib version `0.5.0` .

I use function like that : 
```
const a = pipe(gotenberg(process.env.GOTENBERG), convert, office, please)
```

if I pass a tuples, for example : 
```
a(['aaaa', <readableStream>]);
```

I got an error : 
```
Error: There are duplicates in file names: index.html
```

the problem is : 
[here](https://github.com/yumauri/gotenberg-js-client/blob/master/src/internal/source-converters.ts#L120)

the variable `tuples` contain an array : 
```
[
  [
    "index.html",
    "aaaa"
  ],
  [
    "index.html",
    <readableStream>
  ]
]
```
so, [here](https://github.com/yumauri/gotenberg-js-client/blob/master/src/please.ts#L42) , we found some duplicates .

---
For informations, [here](https://github.com/yumauri/gotenberg-js-client/blob/master/src/please.ts#L45), 
```
request.source = [
  "aaaa",
  <readableStream>
  }
]
```

**Comment by thib3113** [comment]
Seems logic, because I pass an incorrect fileName . 

But I thinks the error throwed is not really the real error, and can hide some others error

Example, if two strings are passed, did you set the filename to `index.html` two times ? and so, throw an error because duplicate filename ?

Else, because it seems that passing two string, and the first is not a fileName, is not supported, maybe throw an error before the duplicate check

**Comment by yumauri** [comment]
Yeah, there is a check of first argument, if it is filename, [here](https://github.com/yumauri/gotenberg-js-client/blob/master/src/internal/source-converters.ts#L55). Filename should match regular expression `/^[\w\s\(\),-]+\.[A-Za-z0-9]+$/`

But I agree, that error shown points to different direction. I'll check it, thank you!

**Comment by yumauri** [comment]
I've added few more source checks, published version [0.6.0](https://github.com/yumauri/gotenberg-js-client/releases/tag/v0.6.0)

There shouldn't be any breaking changes, but it turned out there are number of commits since last release, so I decided to bump minor version, just in case :)

New checks should catch cases like:

```javascript
['aaaaa', 'test']
{ aaaaa: 'test' }
```

and nested too:

```javascript
[['aaaaa', 'test']]
[{ aaaaa: 'test' }]
[['aaaaa', 'test'], { aaaaa: 'test' }]
```

(Error will be thrown only on first item)

**Comment by yumauri** [comment]
@thib3113 do you think this is enough?

I thought about adding link to [Source documentation](https://github.com/yumauri/gotenberg-js-client/wiki/Source) in error message, but decided against, this looks like React-like overkill to me :)

**Comment by thib3113** [comment]
yes I think . Next time I got this error, I will faster know I passed an incorrect filename xD, insteed of searching why my file is named index.html ;) .

thank you

**Comment by yumauri** [comment]
Cool :) Closing this then
