### ISSUE TITLE
Add Merge function usage in documentation like Convert. (How use merge ?)

### ISSUE THREAD

**Issue by epiphaneSpecter** [yumauri/gotenberg-js-client#13]
For two days I have been hard at work merging three files, but unfortunately it still does not work.
I do something like this:

```javascript
const toMergedPDF = pipe(
            gotenberg('http://localhost:3000'),
            merge,
            please,
        )

const mPdf = await toMergedPDF(
                 [
                     ['file.pdf', 'file://file.pdf'],
                     ['file2.pdf', 'file://file2.pdf'],
                     ['file3.pdf', 'file://file3.pdf'],
                  ]
            )

mPdf.pipe(fs.createWriteStream('final.pdf'));

```

**Comment by yumauri** [comment]
Hello! You are doing it correctly.

The issue in that code, I guess, is that library couldn't find files by that paths, try to be more explicit in where they are, for example:

```javascript
  const mPdf = await toMergedPDF([
    ['file.pdf', `file://${__dirname}/file.pdf`],
    ['file2.pdf', `file://${__dirname}/file2.pdf`],
    ['file3.pdf', `file://${__dirname}/file3.pdf`],
  ])
  mPdf.pipe(fs.createWriteStream(`${__dirname}/final.pdf`))
```

Also when you specify source by file URI, you can omit filename (if you don't want to override it, of course):

```javascript
  const mPdf = await toMergedPDF([
    `file://${__dirname}/file.pdf`,
    `file://${__dirname}/file2.pdf`,
    `file://${__dirname}/file3.pdf`,
  ])
  mPdf.pipe(fs.createWriteStream(`${__dirname}/final.pdf`))
```

**Comment by yumauri** [comment]
I tried my second example without filenames and it doesn't work, I'll check it later...
But first one works like charm in my case :)

**Comment by epiphaneSpecter** [comment]
ok i try and i get back to you.
thank you so much. :)

**Comment by yumauri** [comment]
I've uploaded test file, it creates three PDF files, and then merges them. You can try it from repo clone:

First, run Gotenberg:
```
docker run --rm -p 3500:3000 thecodingmachine/gotenberg:6
```

Then script:
```
npx ts-node -O '{"module":"commonjs"}' test/manual/test_issue_13.ts
```

It should create four PDF files next to itself.

**Comment by epiphaneSpecter** [comment]
> I've uploaded test file, it creates three PDF files, and then merges them. You can try it from repo clone:
> 
> First, run Gotenberg:
> 
> ```
> docker run --rm -p 3500:3000 thecodingmachine/gotenberg:6
> ```
> 
> Then script:
> 
> ```
> npx ts-node -O '{"module":"commonjs"}' test/manual/test_issue_13.ts
> ```
> 
> It should create four PDF files next to itself.

I got this error

`
npx ts-node -O '{"module":"commonjs"}' test/manual/test_issue_13.ts
undefined:1
'{module:commonjs}'
^
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at parse (E:\OTHERS\gotenberg-js-client\node_modules\ts-node\dist\index.js:103:45)
    at arg (E:\OTHERS\gotenberg-js-client\node_modules\arg\index.js:122:24)
    at main (E:\OTHERS\gotenberg-js-client\node_modules\ts-node\dist\bin.js:34:18)
    at Object.<anonymous> (E:\OTHERS\gotenberg-js-client\node_modules\ts-node\dist\bin.js:446:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)`

**Comment by yumauri** [comment]
Looks like you are using Windows, I don't have Windows at my hands right now, did a quick search and, [perhaps, you can try](https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter)

```
npx ts-node -O '{^"module^":^"commonjs^"}' test/manual/test_issue_13.ts
```

or maybe with backslashes:

```
npx ts-node -O '{^"module^":^"commonjs^"}' test\manual\test_issue_13.ts
```

**Comment by epiphaneSpecter** [comment]
I defined the links to the files in absolute, but I still have an **error: 500.** I checked the server is easily accessible. I also increased the _waitTimeout to 30 seconds._

**Comment by yumauri** [comment]
Whats in the error message?
Also, can you try to run Gotenberg with `-e LOG_LEVEL=DEBUG` and show, what Gotenberg writes about in the log?

**Comment by epiphaneSpecter** [comment]
Example of my link when i do console.log
`file://E:\\directory1\\directory2\\directory3\\file3.pdf`

**Comment by epiphaneSpecter** [comment]
> Whats in the error message?
> Also, can you try to run Gotenberg with `-e LOG_LEVEL=DEBUG` and show, what Gotenberg writes about in the log?

**ok**

**Comment by epiphaneSpecter** [comment]
My log file
`
{"bytes_in":"262052","bytes_out":"79","host":"localhot:3000","latency":"298623056","latency_human":"298.623056ms","level":"error","method":"POST","msg":"request failed","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"serverIP","status":500,"time":"2020-05-20T16:20:09Z","trace":"e6XoFYKZ7nFnEwXijnyCLF5fsVbGmw8H","uri":"/merge","user_agent":""}
`

**Comment by epiphaneSpecter** [comment]
> My log file
> `{"bytes_in":"262052","bytes_out":"79","host":"localhot:3000","latency":"298623056","latency_human":"298.623056ms","level":"error","method":"POST","msg":"request failed","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"serverIP","status":500,"time":"2020-05-20T16:20:09Z","trace":"e6XoFYKZ7nFnEwXijnyCLF5fsVbGmw8H","uri":"/merge","user_agent":""}`

the error message is just : request failed

**Comment by yumauri** [comment]
Hm... to be sure this is an issue with library — can you try to send files directly to Gotenberg? For example, using `curl` tool, or any other http client?

**Comment by epiphaneSpecter** [comment]
> Hm... to be sure this is an issue with library — can you try to send files directly to Gotenberg? For example, using `curl` tool, or any other http client?

### ok

**Comment by epiphaneSpecter** [comment]
`
{"level":"debug","msg":"merging '[/gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file.pdf /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file2.pdf /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file3.pdf]'...","op":"printer.mergePrinter.Print","time":"2020-05-20T18:22:13Z","trace":"gB7djzIpRq3WymCdfDj4JIvJA2sLmscS"}

{"level":"debug","msg":"executing command: pdftk /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file.pdf /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file2.pdf /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file3.pdf cat output /gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/CaS5Yq9NSlWFJVUPgWYORroX4xa4wBpy.pdf","op":"xexec.LogBeforeExecute","time":"2020-05-20T18:22:13Z","trace":"gB7djzIpRq3WymCdfDj4JIvJA2sLmscS"}

{"level":"debug","msg":"Error: Unable to find file.","op":"stderr.pdftk./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file.pdf./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file2.pdf./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file3.pdf.cat.output./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/CaS5Yq9NSlWFJVUPgWYORroX4xa4wBpy.pdf","time":"2020-05-20T18:22:14Z","trace":"gB7djzIpRq3WymCdfDj4JIvJA2sLmscS"}

{"level":"debug","msg":"Error: Failed to open PDF file: ","op":"stderr.pdftk./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file.pdf./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file2.pdf./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/file3.pdf.cat.output./gotenberg/tmp/gB7djzIpRq3WymCdfDj4JIvJA2sLmscS/CaS5Yq9NSlWFJVUPgWYORroX4xa4wBpy.pdf","time":"2020-05-20T18:22:14Z","trace":"gB7djzIpRq3WymCdfDj4JIvJA2sLmscS"}

`

**Comment by yumauri** [comment]
This is log when you send files directly to Gotenberg? Can you share you PDF files? Maybe they are corrupted?

**Comment by epiphaneSpecter** [comment]
> This is log when you send files directly to Gotenberg? Can you share you PDF files? Maybe they are corrupted?
 _This is log when you send files directly to Gotenberg?_ : **for both, I have the same error**
_Can you share you PDF files? Maybe they are corrupted?_ : **they are well readable**  first I generate them and then I would like to be able to merge them to have a single file. these are statements for different months

**I also tried buffer** 
I send buffer like that, but i still get an error
[
  [ 'file.pdf', <Buffer > ],
  [ 'file2.pdf', <Buffer > ],
  [ 'file3.pdf', <Buffer > ]
]
**on my console**
Error: 500 Internal Server Error (an internal error has occurred: please contact technical support)
    at IncomingMessage.<anonymous> (E:\chatbot\chatbot-banking-webhook\node_modules\gotenberg-js-client\dist-node\index.js:44:18)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`
**in the log the same error**

**my gottenberg container is online. he is not on localhost**

**Comment by yumauri** [comment]
Can you share you PDF files? Maybe fill them with fake data, if you aware of privacy?
So I can try to merge them on my machine.

Also, can you try merging another PDF files?

**Comment by epiphaneSpecter** [comment]
> Can you share you PDF files? Maybe fill them with fake data, if you aware of privacy?
> So I can try to merge them on my machine.
> 
> Also, can you try merging another PDF files?

[file.pdf](https://github.com/yumauri/gotenberg-js-client/files/4659307/file.pdf)
[file2.pdf](https://github.com/yumauri/gotenberg-js-client/files/4659308/file2.pdf)
[file3.pdf](https://github.com/yumauri/gotenberg-js-client/files/4659309/file3.pdf)

**Comment by yumauri** [comment]
Thank you! I tried to merge them, and there are no issues... I tried it from code, using library, and directly using `curl` — either way works just fine on my machine...

```
curl --request POST --url http://localhost:3500/merge --header 'Content-Type: multipart/form-data' --form files=@file.pdf --form files=@file2.pdf --form files=@file3.pdf -o result.pdf
```

Do you have latest Gotenberg docker image? Just in case.

Maybe there are some issues with remote host machine? No disk space, for example? Docker has exceeded disk limits? No free inodes?

Maybe this is related to your Windows somehow, but I doubt it.

**Comment by epiphaneSpecter** [comment]
> Thank you! I tried to merge them, and there are no issues... I tried it from code, using library, and directly using `curl` — either way works just fine on my machine...
> 
> ```
> curl --request POST --url http://localhost:3500/merge --header 'Content-Type: multipart/form-data' --form files=@file.pdf --form files=@file2.pdf --form files=@file3.pdf -o result.pdf
> ```
> 
> Do you have latest Gotenberg docker image? Just in case.
> 
> Maybe there are some issues with remote host machine? No disk space, for example? Docker has exceeded disk limits? No free inodes?
> 
> Maybe this is related to your Windows somehow, but I doubt it.

Ok tanks, i Will check your suggestions.

**Comment by yumauri** [comment]
Were you able to find an issue cause? If someone will stumble upon similar issue in future

**Comment by epiphaneSpecter** [comment]
not yet. but I don't think the problem comes from here. So I close the issue, if I find a solution I will come and put it. :-)

**Comment by hermann-p** [comment]
I had similar issues with seemingly arbitrary error messages -- until I made sure the files I sent were not only marked as PDF but also had associated file names ending in `.pdf` -- from there on it worked like a charm (in my case I generated two files from different templates via gotenberg and passed the resulting streams through to the merge endpoint).
