### ISSUE TITLE
Can I convert docx from Buffer?

### ISSUE THREAD

**Issue by shaharsol** [yumauri/gotenberg-js-client#15]
In the Readme it shows how to convert HTML by passing a string. Let's say I have the docx in a Buffer, can I use it to convert to PDF, instead of having to save it to the filesystem only to be able to post it to gotenberg?

**Comment by yumauri** [comment]
Yes, sure! [Source](https://github.com/yumauri/gotenberg-js-client/wiki/Source) can be Buffer:

```javascript
const toPDF = pipe(
  gotenberg('http://localhost:3000'),
  convert,
  office,
  please
)

// --- 8< ---

const buffer = ...
const pdf = await toPDF({ 'document.docx': buffer })
```

**Comment by yumauri** [comment]
I've added [few lines to README file](https://github.com/yumauri/gotenberg-js-client#office--gotenberg-documentation), with example of streaming downloaded file to Gotenberg, without saving it to the disk.
