### ISSUE TITLE
Files not found were they're not located on the root folder

### ISSUE THREAD

**Issue by Esteban26** [yumauri/gotenberg-js-client#18]
It seems to have problems with the paths, I was passing the value file:///Users/myuser/file/to/my/project/file.docx 

And it retrieves the error:

POST /convert/office 404 9.323 ms - 33
error: General error while uploading a document. 404 Not Found (undefined) {"stack":"Error: 404 Not Found (undefined)\n    at IncomingMessage.<anonymous> (/Users/estebanhernandez/Documents/HD/sharedocview/server/node_modules/gotenberg-js-client/dist-node/index.js:44:18)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
error: 404 Not Found (undefined)

**Comment by yumauri** [comment]
Hello!

I think this is not related to file location,

> POST /convert/office 404 9.323 ms - 33

this looks more like you either didn't deploy Gotenberg correctly, or you have wrong Gotenberg URL in `gotenberg` function.
Can you show your code, please?

**Comment by yumauri** [comment]
@Esteban26 ?

**Comment by yumauri** [comment]
Due to lack of response I will close this issue.
@Esteban26 feel free to reopen, if you still experience this problem.
