### ISSUE TITLE
Option to add http/https agent of my own.

### ISSUE THREAD

**Issue by adame21** [yumauri/gotenberg-js-client#28]
Hi,

What I want to be able to do is send my own HTTP/HTTPS agent - this is to be able to set keepAlive: true.

I tried looking through the library's code but couldn't find a way. (could barely understand what was going on - inexperienced with ts)

Does this option exist today?
Is it possible to add or make a workaround in my project to set it like this?

If its not possible I will have to "wrap" the gotenberg client myself which I really try to avoid.

Thanks :)
Update:
I just noticed you added "adjust" in your latest version. 
It looks like it might be able to do what I need.
Can you let me know if this code does it ?
````javascript
            const toPDF = pipe(
                gotenberg(getVariableValue("GOTENBERG_BASE_URL")),
                convert,
                html,
                // set({
                //     waitDelay: "1.5"
                // }),
                adjust({
                    httpsAgent: new https.Agent({
                        keepAlive: true,
                        maxSockets: 1
                    })
                }),
                to({
                    marginTop: margin.top,
                    marginBottom: margin.bot,
                    marginLeft: margin.left,
                    marginRight: margin.right,
                    landscape
                }),
                please
            )

````

**Comment by yumauri** [comment]
Hello!

You can do it :) Actually, there are few options (none is documented though...). But not with `adjust` — this function can be used to change internal request object, this is not _actual_ HTTP request.

1.

Function `gotenberg` actually accepts from one to three arguments:

- URL to Gotenberg instance
- HTTP Client
- Config for HTTP Client

It tries to guess type of a second argument, and if it is not HTTP client — it is considered to be config for embeded client.
Reqular Node.js [http.request](https://nodejs.org/api/http.html#http_http_request_url_options_callback) and [https.request](https://nodejs.org/api/https.html#https_https_request_url_options_callback) are used in embeded client, so you should be able to add any available options here, for example:

```javascript
gotenberg(
  getVariableValue("GOTENBERG_BASE_URL"),
  { agent: new http.Agent({ keepAlive: true }) }
),
```

2.

As stated in the 1, you can create and pass completely your own HTTP client to `gotenberg` function.

HTTP Client (_GotenbergClient_) could be a plain object with fields `post` and optional `get` (`get` is used for _ping_ requests, so if you don't use them, you can omit it), or it could be a function, which will be called with third config argument, and should return object with fields `post` and optional `get`, or it could be a class, which will be instantiated with third config argument, and should have methods `post` and optional `get`.

Then `post` method is called with three arguments:

- url: `string`
- data: `FormData`
- headers?: `{ [header: string]: number | string | string[] | undefined }`

and should return `Promise<NodeJS.ReadableStream>` _(in fact you can return any response format you want from your client — this response will be returned from the whole pipe execution)_

**Comment by yumauri** [comment]
_Sidenote about point 1:_
If you want to use same `http.Agent` for all requests, you should create is once, obviously. Best way is to define `toPDF` function once, like global one (don't create it each time you want to convert your documents). Or create `http.Agent` once, and use link to it in `pipe` execution.
If you will create `toPDF` function each time, and creates `http.Agent` each time — this will be useless, because each request will use separate Agent.

**Comment by adame21** [comment]
Hi !
Thanks so much for such a fast and elaborate response.
I am testing both options and seeing what works best for my case.
Your sidenote about point 1 was very important to me as I do actually create toPdf every time, but its mainly because the margins arent always the same.
So if I wish to change one of the parameters passed to gotenberg func I have to re-create it ?
Regardless, I will use this advice, and close this issue by then end of the day with my results.
Thanks again !

**Comment by yumauri** [comment]
_Sidenote about point 2:_

Here are different examples of custom HTTP client, based on [got](https://github.com/sindresorhus/got) library (I didn't try them though, but to show an idea it should be enough):

1. Plain object:

```javascript
const client = {
  post(url, body, headers) {
    return got.post(url, { body, headers })
  }
}
```

2. Function

```javascript
function client(config) {
  // you can use config here for some preparations
  return {
    post(url, body, headers) {
      return got.post(url, { body, headers })
    }
  }
}
```

3. Class

```javascript
class client {
  constructor(config) {
    // you can use config here for some preparations
  }

  post(url, body, headers) {
    return got.post(url, { body, headers })
  }
}
```

Then you can use this client in `gotenberg` function:

```javascript
gotenberg(
  getVariableValue("GOTENBERG_BASE_URL"),
  client, // one of the clients from above
  config // any config for your client
),
```

**Comment by yumauri** [comment]
Note, that you can't change conversion type in partial pipe application, because `convert` and `html` (`office`/`markdown`/...) functions are adding _path_ part to the url. So if you try to do smth like this:

```javascript
pipe(
  gotenberg(...),
  convert,
  url,
  html,
  ...
)
```

It will use path `gotenberg/convert/url/html`, which is not a valid path for Gotenberg.

But I've got you covered, and made an exception for such case :) Following issue #14

But overriding margings, paper size, orientation and any headers should work fine.

**Comment by yumauri** [comment]
Sorry for amount of comments :)

You also can make smth like this:

```javascript
// define this globally
const myGotenberg = gotenberg(
  getVariableValue("GOTENBERG_BASE_URL"),
  { agent: new http.Agent({ keepAlive: true }) }
)

// then use this function in pipe

const toPDF = pipe(
  myGotenberg,
  convert,
  html,
  to({
    marginTop: margin.top,
    marginBottom: margin.bot,
    marginLeft: margin.left,
    marginRight: margin.right,
    landscape
  }),
  please
)
```

**Comment by adame21** [comment]
Hello,
My mind is blown by this amazing support.
I hope I can repay this kindness somehow.
I decided to simply create an https agent on the top of the module (as in - same agent every time)
I use two different functions for office and html so no problem there.
I still create toPdf every time, but I use the same agent.
It works muy bueno.
Again your support was amazing, thank you so much.
I'm happy for anyone with the same question stumbling to this issue. 
:)
