### ISSUE TITLE
Gotenberg 6.1.0

### ISSUE THREAD

**Issue by gulien** [yumauri/gotenberg-js-client#3]
Hello :)

FYI, I've just released Gotenberg [6.1.0](https://github.com/thecodingmachine/gotenberg/releases/tag/6.1.0) 🎉 

Here is an example with the new features implemented in the go client: https://github.com/thecodingmachine/gotenberg-go-client/releases/tag/v7.0.0

**Comment by yumauri** [comment]
Awesome! Thank you so much for keeping me informed!
I'll check new version as soon as I can :)

**Comment by yumauri** [comment]
Published new version [0.4.0](https://github.com/yumauri/gotenberg-js-client/releases/tag/v0.4.0) with custom HTTP headers and page ranges support!
