### ISSUE TITLE
cannot find name URL

### ISSUE THREAD

**Issue by ashiishme** [yumauri/gotenberg-js-client#37]
The `_types.ts` & `gotenberg.ts` is missing the URL import which throws error when building the project ( hopefully I think only backend ) that depends on Gotenberg service.

```
Error: node_modules/gotenberg-js-client/dist-types/_types.d.ts(68,30): error TS2304: Cannot find name 'URL'.
Error: node_modules/gotenberg-js-client/dist-types/gotenberg.d.ts(3,57): error TS2304: Cannot find name 'URL'.
```

To re-create:

- Use gotenberg-js-client on backend project
- Build the project

**Comment by yumauri** [comment]
Hello!
`URL` class is available globally in Node.js since version 10, but [still wasn't added to node types](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960) ._.
As a temporary solution you can add `"dom"` to your `tsconfig.json` libs.

**Comment by ashiishme** [comment]
Thank you for giving more insight of the issue. Is there any other alternatives rather than using "dom"?

**Comment by yumauri** [comment]
I tried to add
```typescript
import { URL } from 'url'
```
to where `URL` is used.

Can you try version 0.7.1, will it work out for you?

**Comment by yumauri** [comment]
BTW, for now, this is _backend only_ client, because it heavily relies on Node.js internals

**Comment by ashiishme** [comment]
@yumauri  Thank you for the new release. Yes, it resolved the TS complain about URL.
