### ISSUE TITLE
Source name "Screenshot 2021-12-24 at 09.16.20.png" doesn't look like file name

### ISSUE THREAD

**Issue by axelvugts** [yumauri/gotenberg-js-client#38]
It seems like the regex used in [isFileName](https://github.com/yumauri/gotenberg-js-client/blob/ea81f28d446adcc4e61ae8c743a1afb741a7751e/src/internal/source-checkers.ts#L85) to check if something is a valid filename currently cannot handle filenames that contain an additional "." character. Would be great if you could have a look at this sometime :)

**Comment by yumauri** [comment]
Oops, my bad. I'll fix this :)

**Comment by yumauri** [comment]
@axelvugts just published version [0.7.2](https://github.com/yumauri/gotenberg-js-client/releases/tag/v0.7.2), should fix this

**Comment by axelvugts** [comment]
Thanks for the quick fix! It's working as expected now 👍
