### ISSUE TITLE
404 Not found Error

### ISSUE THREAD

**Issue by a0yan** [yumauri/gotenberg-js-client#39]
```  javascript
const {
    pipe,
    gotenberg,
    convert,
    markdown,
    office,
    to,
    landscape,
    set,
    filename,
    please,
  } = require('gotenberg-js-client')
  
  const toPDF = pipe(
    gotenberg('http://localhost:3000'),
    convert,
    office,
    to(landscape),
    set(filename('result.pdf')),
    please
  )
  
  // --- 8< ---
  
  // --- 8< ---
  
app.get('/api/convert_docs',async(req,res)=>{
   
    try {
        const pdf = await toPDF('file://mock_amikus_2.docx')
      
    } catch (error) {
        console.error(error.message)
    }
```

**Comment by yumauri** [comment]
Hello! Does Gotenberg listening on `http://localhost:3000` and if yes — what version of Gotenberg do you use?

**Comment by yumauri** [comment]
@a0yan if you are using Gotenberg version 7.x — this library is not yet fully compatible with it.
Among other things it has changed conversion URLs, so it might cause 404 error.
Please, read [this comment](https://github.com/yumauri/gotenberg-js-client/issues/32#issuecomment-981140727), I've pointed, how you can work around this problem for a while.

**Comment by a0yan** [comment]
@yumauri  Thanxx
