### ISSUE TITLE
Error: 404 Not Found

### ISSUE THREAD

**Issue by Kobylan** [yumauri/gotenberg-js-client#42]
I had a problem converting from html

The documentation says to specify your host

`const toPDF = pipe(
  gotenberg('http://localhost:3000'),
  convert,
  html,
  please
)`

But it gave out Error: 404 Not Found

But if specify `http://localhost:3000/forms/chromium`
it works

I think it's worth mentioning in the documentation =)

**Comment by yumauri** [comment]
Hello!
Thank you for raising an issue :)
This library is not yet fully compatible with Gotenberg 7,
workaround (which you've discovered yourself :)) is mentioned in [this comment](https://github.com/yumauri/gotenberg-js-client/issues/32#issuecomment-981140727).

**Comment by yumauri** [comment]
This issue is not the first issue raised, related to Gotenberg 7, so I've added [nota bene](https://github.com/yumauri/gotenberg-js-client#nb-%EF%B8%8F) in README, thank you :)
