### ISSUE TITLE
word转pdf, typeError [ERR_INVALID_PROTOCOL]: Protocol "d:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by htt828** [yumauri/gotenberg-js-client#52]
async docx2pdf(wordConfigFilePath, pdfConfigFilePath, fileName) {
    const toPDF = pipe(
      gotenberg(path.resolve(pdfConfigFilePath)),
      convert,
      office,
      to(landscape),
      set(filename(fileName + '.pdf')),
      please
    );
    const pdf = await toPDF({ 'fileName.docx': fs.readFileSync(path.resolve(wordConfigFilePath, fileName + '.docx')) });
  },
我想通过docx转pdf 但是出现了这个报错 typeError [ERR_INVALID_PROTOCOL]: Protocol "d:" not supported. Expected "https:"

**Comment by yumauri** [comment]
Did you solve your problem?
