### ISSUE TITLE
What should I fill in the gotenberg parameter in the pipe method

### ISSUE THREAD

**Issue by htt828** [yumauri/gotenberg-js-client#53]

**Comment by yumauri** [comment]
`gotenberg` function accept address of your Gotenberg instance, for example:
```js
gotenberg('http://localhost:3000')
```
if you have Gotenberg running on localhost port 3000

**Comment by htt828** [comment]
ok,thank you

**Comment by htt828** [comment]
but Error: 404 Not Found

**Comment by htt828** [comment]
my code
const toPDF = pipe(
      gotenberg(''),
      convert,
      office,
      to(landscape),
      adjust({
        url: 'http://192.168.1.40:3000/forms/libreoffice/convert',
      }),
      set(filename(fileName + '.pdf')),
      please
    );
    const pdf = await toPDF({ [fileName + '.docx']: fs.createReadStream(path.resolve(wordConfigFilePath, fileName + '.docx')) });


but Error: 500 Internal Server Error  at IncomingMessage.<anonymous> (D:\workspace\jcqlc\node_modules\gotenberg-js-client\dist-node\index.js:46:18)

**Comment by yumauri** [comment]
Does Gotenberg logs some errors to stdout?
Also, does it work fine if you use `curl` (or any other HTTP client) to send file directly to Gotenberg?

**Comment by yumauri** [comment]
I'll close this issue, feel free to reopen it, if you still encounter this problem!
