### ISSUE TITLE
Source name doesn't look like file name

### ISSUE THREAD

**Issue by janswist** [yumauri/gotenberg-js-client#60]
I got this error:  `Error: Source name "ces La esencia del cristianismo Dios es persona (jÃ³venes).docx" doesn't look like file name`

edit: Seems like the issue is not with the name, but that there is [hard cap limit of name length](https://github.com/yumauri/gotenberg-js-client/blob/master/src/internal/source-checkers.ts#L88) of 50 characters. Can we edit it somehow or at least make it bigger? 50 char names are not that rare.

Same thing with the minimum number of 3 characters - users sometimes do have like 1 char names for whatever reason :)

edit: After testing the problem is with `³` character. Exploring why is that.

**Comment by yumauri** [comment]
Hello! Wow, I didn't expect this, especially when you can use any file name, it is not required to be the same, as your real file name. Can you try something like this:

```js
const pdf = await toPDF({
  "Christian Essence - God (Youth).docx":
    fs.createReadStream("ces La esencia del cristianismo Dios es persona (jÃ³venes).docx")
})
```

Or you are not in control of filenames?

I actually am not sure, why I put this limits back then 🤔 I'll try to loosen them and if Gotenberg is fine with new limits, I certainly will publish a fix :) In a few days, I hope

**Comment by yumauri** [comment]
Can you show how do you use library API? Do you use file streams or file names starting with `file://`?

**Comment by yumauri** [comment]
I made filename checks as loose as possible, I think :) Can you try version 0.7.4?

**Comment by janswist** [comment]
Sure, let me try. In the meantime from the old version (I just read your message so before update):
![image](https://github.com/yumauri/gotenberg-js-client/assets/5583954/3fc9d481-0050-4620-a84c-66a5d580d036)


Tested. Now it works, but was strange to not accept %20 characters. Thanks for the fix!

**Comment by janswist** [comment]
> Can you show how do you use library API? Do you use file streams or file names starting with `file://`?

I use files uploaded and streams and they both has `filename` property.

**Comment by yumauri** [comment]
I think I was just trying to make fool-proof protection, but maybe it was not necessary.

Actually file name can contain literally any character, depending on operating system and file system. For example, in JFS file name can contain even `/` char. Also, on MacOS `:` in filenames are showed like `/` in Finder 🙈
<img width="286" alt="image" src="https://github.com/yumauri/gotenberg-js-client/assets/6583994/d91f37fd-c7b2-47ad-8965-db0c6342034c"> <img width="279" alt="image" src="https://github.com/yumauri/gotenberg-js-client/assets/6583994/e08caeed-827c-4f40-b81b-96551b117b9c">

My main concern now is will Gotenberg be fine with those filenames? :)
Is your issue solved?

**Comment by janswist** [comment]
Yes, my issue is solved - for now because one never knows what user will provide as an input 🥲 As for me, the best would be just to drop on it just because of that one reason (and to give freedom to the devs if they want to make a fool-protection). I was taken by surprise after having it on production when users got error with those exotic signs in their file names. 

Regarding Gotenberg itself - I think he doesn't mind and realize that there are too many use cases to cover them all: https://github.com/gotenberg/gotenberg/issues/652 but best to ask him directly, maybe even in that same issue if you like. He's quite responsive so will probably get back to you really fast :)

Thanks for supporting this js client still!
