### ISSUE TITLE
set delay

### ISSUE THREAD

**Issue by PedroHenrique-F** [yumauri/gotenberg-js-client#61]
` 
gotenberg('http://localhost:3000/forms/chromium'),
      convert,
      url,
      set({ waitDelay: 10000 }), 
      request => {
        (
          request.fields as unknown as {
            url: string;
          }
        ).url = request.fields.remoteURL;
        delete request.fields.remoteURL;
        return request;
      },
      please,
    );

`

Why when adding the set({ waitDelay: 10000 }), it stops working?

**Comment by yumauri** [comment]
Hello!
By the URL I assume you use Gotenberg version 7.
Do you see any errors in Gotenberg?
As far as I see in documentation — https://gotenberg.dev/docs/routes#wait-before-rendering — in version 7 this field has different format. Try this (maybe it will also require TypeScript soothing):
```js
set({ waitDelay: '10s' }),
```

**Comment by yumauri** [comment]
In version 6 `waitDelay` is set in _seconds_, so `10000` is about 3 hours. I guess it is not what you expect.
Maybe version 7 also accepts numbers, try also
```
set({ waitDelay: 10 }),
```

**Comment by yumauri** [comment]
@PedroHenrique-F did you fix an issue with my suggestions?

**Comment by yumauri** [comment]
I assume you've either fixed your issue, with or without my help, or moved on, maybe with another library.
I'll close this issue, but feel free to reopen it if my suggestions didn't help.
