### ISSUE TITLE
Adding page numbers to PDF

### ISSUE THREAD

**Issue by DeyvinC** [yumauri/gotenberg-js-client#64]
Hello @yumauri ,

I am currently using your package for converting my html files into pdf files. Thanks a lot by the way. 
But I'm running into a small issue. Is there any way to show page numbers on the generated PDF? For example  "Page 1 of 3" and etc.
I tried doing it in html but I believe the issue is when it comes down to the conversion html only reads one whole page but pdf converts it into multiple. 

Your help would be greatly appreciated.

**Comment by yumauri** [comment]
Hello! Thank you for using my library, even though it was last updated long ago, and I still have it (upgrade to support latest Gotenberg) in my list 😅

Did you try adding footer, like it states in Gotenberg documentation?
https://gotenberg.dev/docs/routes#header-footer-chromium

```html
<html>
<head>
    <style>
    body {
        font-size: 8rem;
        margin: 4rem auto;
    }
    </style>
</head>
<body>
<p><span class="pageNumber"></span> of <span class="totalPages"></span></p>
</body>
</html>
```

**Comment by yumauri** [comment]
Also the same in the documentation for Gotenberg version 6, if you use it:
https://gotenberg.dev/docs/6.x/html#header-and-footer

**Comment by DeyvinC** [comment]
Awesome thank you. I was looking at those docs but wasn't completely sure if it was also related to this npm package but thank you. The body style was the issue on why I couldn't see it. Got rid of that styling and now its visible.

**Comment by yumauri** [comment]
Did you resolve your question, can I close this issue? :)

**Comment by yumauri** [comment]
I conclude that you have resolved issue, so I'll close this one. Feel free to reopen it in case you experience problem again 👍
