### ISSUE TITLE
how shall i pass my files routes

### ISSUE THREAD

**Issue by Artagos** [yumauri/gotenberg-js-client#66]
i have tried giving global path and a path based on the working directory, it hasnt worked

**Comment by yumauri** [comment]
Inside library it just removes `file://` prefix and creates read stream:
https://github.com/yumauri/gotenberg-js-client/blob/6b58a8b64ecdff56e42f558c0bd29a9076215e13/src/internal/source-converters.ts#L91-L97

So `"file://<absolute path>"` should work.

Also you can specify sources in many forms, not just file paths. You can read file and give library a stream or a buffer, for example.

You can read full source description here — https://github.com/yumauri/gotenberg-js-client/wiki/Source

**Comment by Artagos** [comment]
Thanks a lot, `"file://<absolute path>"` worked for me
