### ISSUE TITLE
Cannot convert xls file due to "context deadline exceeded"

### ISSUE THREAD

**Issue by billkim84** [yumauri/gotenberg-js-client#7]
I'm trying to convert xls file(185KB) but always got "context deadline exceeded" error. 

I set timeout 30 and pageRanges '1-10' but no luck.

tested using thecodingmachine/gotenberg:6

curl --request POST \
    --url http://localhost:3001/convert/office \
    --header 'Content-Type: multipart/form-data' \
    --form files=@test.xls \
    --form waitTimeout=30 \
    --form pageRanges='1-10' \
    -o result.pdf

in the excel file there are 1656 rows and 3 columns. Looks like this. 
![image](https://user-images.githubusercontent.com/2604192/73908340-b0911000-48ec-11ea-9a7e-83dae13ed2ff.png)

Is there any way to set timeout more than 30 seconds, or any way to convert partial without "context deadline exceeded" error???

**Comment by billkim84** [comment]
When I use thecodingmachine/gotenberg:5, it converts excel file without any issue.

**Comment by yumauri** [comment]
Hello, @billkim84 !
I guess, this should be reported to [Gotenberg itself](https://github.com/thecodingmachine/gotenberg/issues), I'm not taking any part in Gotenberg's development, `gotenberg-js-client` is just client ;)

**Comment by billkim84** [comment]
Hi, @yumauri 

I thought I was in Gotenberg repository. :sweat_smile:

Thank you!!
