### ISSUE TITLE
Gotenberg 6.2.0

### ISSUE THREAD

**Issue by gulien** [yumauri/gotenberg-js-client#8]
Hello 😄 

A quick "issue" to let you know that Gotenberg 6.2.0 accepts a new form field `scale` for HTML, URL and Markdown conversions (see https://thecodingmachine.github.io/gotenberg/#html.paper_size_margins_orientation_scaling).

Thank you again for this client 👍

**Comment by yumauri** [comment]
Hello! Cool, thank you!
Added to my task list :)

**Comment by yumauri** [comment]
Published new version [0.5.0](https://github.com/yumauri/gotenberg-js-client/releases/tag/v0.5.0) with scale support!
